version: "3.7"
services:
    ### Plex ###
    # Media Server
    plex:
        container_name: plex
        image: linuxserver/plex:latest
        restart: unless-stopped
        ports:
            # Plex Media Server
            - "32400:32400"
            # Plex DLNA Server
            - "1900:1900/udp"
            - "32469:32469"
            # Plex Home Theater via Plex Companion
            - "3005:3005"
            # Older Bonjour/Avahi network discovery
            #- "5353:5353/udp"
            # Plex for Roku via Plex Companion
            - "8324:8324"
            # GDM network discovery
            - "32469:32469/udp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp"
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            HOSTNAME: "Plex Server"
            VERSION: docker
        volumes:
            - /mediaserver/plex/config:/config
            - /mediaserver/plex/transcode:/transcode
            - /mediaserver/plex/data:/data
            - /mediaserver/movies:/movies
            - /mediaserver/tv:/tv
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            media-server:
                ipv4_address: 172.60.0.2
    
    ### Tautulli ###
    # Plex Monitor
    tautulli:
        container_name: tautulli
        image: linuxserver/tautulli:latest
        restart: unless-stopped
        ports:
            - "8181:8181"
        volumes:
            - /mediaserver/tautulli/config:/config
            - /mediaserver/tautulli/logs:/logs:ro
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            media-server:
                ipv4_address: 172.60.0.3
        
    ### Radarr ###
    # Movie Downloader and Manager
    radarr:
        container_name: radarr
        image: linuxserver/radarr:latest
        restart: unless-stopped
        ports:
            - "7878:7878"
        volumes:
            - /mediaserver/radarr/config:/config
            - /mediaserver/downloads:/completed
            - /mediaserver/movies:/movies
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            media-server:
                ipv4_address: 172.60.0.4
    ### Sonarr ###
    # Serie Downloader and Manager
    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr:latest
        restart: unless-stopped
        ports:
            - "8989:8989"
        volumes:
            - /mediaserver/sonarr/config:/config
            - /mediaserver/downloads:/completed
            - /mediaserver/tv:/tv
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            media-server:
                ipv4_address: 172.60.0.5

    ### Bazarr ###
    # Subtitles Downloader and Manager
    bazarr:
        container_name: bazarr
        image: linuxserver/bazarr:latest
        restart: unless-stopped
        volumes:
            - /mediaserver/bazarr/config:/config
            - /mediaserver/movies:/movies
            - /mediaserver/tv:/tv
        ports:
            - "6767:6767"
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        networks:
            media-server:
                ipv4_address: 172.60.0.6
    
    ### Jackett ###
    # Proxy Server for Sonarr & Radarr search queries
    jackett:
        container_name: jackett
        image: linuxserver/jackett:latest
        restart: unless-stopped
        ports:
            - "9117:9117"
        volumes:
            - /mediaserver/jackett/config:/config/Jackett
            - /mediaserver/downloads:/completed
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            media-server:
                ipv4_address: 172.60.0.7
    
    ### Transmission ###
    # Torrent Client with VPN
    transmission:
        container_name: transmission
        image: haugene/transmission-openvpn:latest
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        devices:
            # See (https://www.kernel.org/doc/Documentation/networking/tuntap.txt)
            - /dev/net/tun
        ports:
            # Web UI
            - "9091:9091"
            # Torrent Port
            - "51413:51413"
            - "51413:51413/udp"
        dns:
            - 1.1.1.1
            - 1.0.0.1
        volumes:
            - /mediaserver/transmission/config:/config
            - /mediaserver/transmission/data:/data
            - /mediaserver/downloads:/downloads
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
            TRANSMISSION_RPC_HOST_WHITELIST: 127.0.0.1,192.168.*.*
            TRANSMISSION_RPC_USERNAME: ${TORRENT_USERNAME}
            TRANSMISSION_RPC_PASSWORD: ${TORRENT_PASSWORD}
            TRANSMISSION_RATIO_LIMIT: 2.00
            TRANSMISSION_RATIO_LIMIT_ENABLED: "false"
            TRANSMISSION_RENAME_PARTIAL_FILES: "true"
            # This will give the service read and execute permissions within the docker group
            TRANSMISSION_UMASK: 022
            TRANSMISSION_DOWNLOAD_DIR: /downloads/completed
            TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
            TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
            TRANSMISSION_WATCH_DIR: /downloads
            TRANSMISSION_WATCH_DIR_ENABLED: "true"
            OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
            CREATE_TUN_DEVICE: "true"
            WEBPROXY_ENABLED: "false"
            # Get access to the WebUI without VPN
            LOCAL_NETWORK: 192.168.0.0/24
            # Set these variables to the preferred VPN
            OPENVPN_USERNAME: ${OPENVPN_USERNAME}
            OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
            # NordVPN specific settings
            OPENVPN_PROVIDER: NORDVPN
            NORDVPN_COUNTRY: CH
            NORDVPN_CATEGORY: P2P
            NORDVPN_PROTOCOL: tcp
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            media-server:
                ipv4_address: 172.60.0.8
        

#    ### Deluge ###
#    # Torrent Client without VPN
#    deluge:
#        container_name: deluge
#        image: linuxserver/deluge:latest
#        restart: unless-stopped
#        ports:
#            # Web UI
#            - "8112:8112"
#            # Incoming Connections (Used for seeding)
#            - "53160:53160"
#            - "53160:53160/udp"
#            # Daemon remote port (Used for GTK applications)
#            - "58846:58846"
#        volumes:
#            - /mediaserver/deluge/config:/config
#            - /mediaserver/downloads:/root/Downloads
#        environment:
#            PUID: ${PUID}
#            PGID: ${PGID}
#            TZ: ${TZ}
#            DELUGE_LOGLEVEL=error
#        labels:
#            com.centurylinklabs.watchtower.enable: true
#        networks:
#            media-server:
#                ipv4_address: 172.60.0.8
    
    ### Watchtower ###
    # Automates Docker Image Updates
    # where `com.centurylinklabs.watchtower.enable: true` is added to the container
    watchtower:
        container_name: watchtower
        image: v2tec/watchtower:latest
        restart: unless-stopped
        # Watch containers where `com.centurylinklabs.watchtower.enable: true`
        # Update every Monday at 4 AM
        # seconds - minutes - hours - day of month - month - day of week
        command: --label-enable --schedule "0 0 4 * * 1" --cleanup
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            TZ: ${TZ}
        networks:
            media-server:
                ipv4_address: 172.60.0.9

networks:
    media-server:
        name: media-server
        ipam: # IP Address Management
            driver: default
            config:
                - subnet: 172.60.0.0/16
