version: "3.7"
services:
    ### Plex ###
    # Media server
    plex:
        container_name: plex
        image: linuxserver/plex:latest
        restart: unless-stopped
        hostname: plex
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            HOSTNAME: "Plex Server"
            VERSION: docker
        volumes:
            - /media-server/plex/config:/config
            - /media-server/plex/transcode:/transcode
            - /media-server/plex/data:/data
            - /media-server/movies:/movies
            - /media-server/music:/music
            - /media-server/series:/series
        ports:
            # Plex Media Server
            - "32400:32400"
            # Plex DLNA Server
            - "1900:1900/udp"
            - "32469:32469"
            # Plex Home Theater via Plex Companion
            - "3005:3005"
            # Older Bonjour/Avahi network discovery
            #- "5353:5353/udp"
            # Plex for Roku via Plex Companion
            - "8324:8324"
            # GDM network discovery
            - "32469:32469/udp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp"
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            - media-server
    
    ### Tautulli ###
    # Plex monitor
    tautulli:
        container_name: tautulli
        image: linuxserver/tautulli:latest
        restart: unless-stopped
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - /media-server/tautulli/config:/config
            - /media-server/tautulli/logs:/logs:ro
        ports:
            - "8181:8181"
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            - media-server
        
    ### Radarr ###
    # Movie downloader and manager
    radarr:
        container_name: radarr
        image: linuxserver/radarr:nightly
        restart: unless-stopped
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - /media-server/radarr/config:/config
            - /media-server/downloads/completed:/downloads/completed
            - /media-server/movies:/movies
        ports:
            - "7878:7878"
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            - media-server

    ### Sonarr ###
    # Serie downloader and manager
    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr:preview
        restart: unless-stopped
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - /media-server/sonarr/config:/config
            - /media-server/downloads/completed:/downloads/completed
            - /media-server/series:/series
        ports:
            - "8989:8989"
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            - media-server

    ### Bazarr ###
    # Subtitles downloader and manager
    bazarr:
        container_name: bazarr
        image: linuxserver/bazarr:latest
        restart: unless-stopped
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - /media-server/bazarr/config:/config
            - /media-server/movies:/movies
            - /media-server/series:/series
        ports:
            - "6767:6767"
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            - media-server
            
    ### Lidarr ###
    # Music downloader and manager
    lidarr:
        container_name: lidarr
        image: linuxserver/lidarr:latest
        restart: unless-stopped
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}    
        volumes:
            - /media-server/lidarr/config:/config
            - /media-server/music:/music
            - /media-server/downloads/completed:/downloads/completed
        ports:
            - "8686:8686"
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            - media-server
            
    ### Ombi ###
    # Plex requests and user management system
    ombi:
        container_name: ombi
        image: linuxserver/ombi:latest
        restart: unless-stopped
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - /media-server/ombi/config:/config
        ports:
            - "3579:3579"
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            - media-server
    
    ### Jackett ###
    # Proxy Server for Sonarr & Radarr search queries
    jackett:
        container_name: jackett
        image: linuxserver/jackett:latest
        restart: unless-stopped
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - /media-server/jackett/config:/config/Jackett
            - /media-server/downloads/completed:/downloads/completed
        ports:
            - "9117:9117"
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            - media-server
    
    ### Transmission ###
    # Torrent client with VPN
    transmission:
        container_name: transmission
        image: haugene/transmission-openvpn:latest
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        devices:
            # See (https://www.kernel.org/doc/Documentation/networking/tuntap.txt)
            - /dev/net/tun
        dns:
            - 1.1.1.1
            - 1.0.0.1
            - 8.8.8.8
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
            TRANSMISSION_RPC_HOST_WHITELIST: 127.0.0.1,192.168.*.*
            TRANSMISSION_RPC_USERNAME: ${TORRENT_USERNAME}
            TRANSMISSION_RPC_PASSWORD: ${TORRENT_PASSWORD}
            TRANSMISSION_RATIO_LIMIT: 0
            TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
            TRANSMISSION_RENAME_PARTIAL_FILES: "true"
            # This will give the service read and execute permissions within the docker group
            TRANSMISSION_UMASK: 022
            TRANSMISSION_DOWNLOAD_DIR: /downloads/completed
            TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
            TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
            TRANSMISSION_WATCH_DIR: /downloads/watch
            TRANSMISSION_WATCH_DIR_ENABLED: "true"
            OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
            CREATE_TUN_DEVICE: "true"
            WEBPROXY_ENABLED: "false"
            # Get access to the WebUI without VPN
            LOCAL_NETWORK: 192.168.0.0/24
            # Set these variables to the preferred VPN
            OPENVPN_USERNAME: ${OPENVPN_USERNAME}
            OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
            # NordVPN specific settings
            OPENVPN_PROVIDER: NORDVPN
            NORDVPN_COUNTRY: CH
            NORDVPN_CATEGORY: P2P
            NORDVPN_PROTOCOL: tcp
        volumes:
            - /media-server/transmission/config:/config
            - /media-server/transmission/data:/data
            - /media-server/downloads/watch:/downloads/watch
            - /media-server/downloads/completed:/downloads/completed
            - /media-server/downloads/incomplete:/downloads/incomplete
        ports:
            # Web UI
            - "9091:9091"
            # Torrent Port
            - "51413:51413"
            - "51413:51413/udp"
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            - media-server
    
    ### Watchtower ###
    # Automates Docker image updates
    # where `com.centurylinklabs.watchtower.enable: true` is added to the container
    watchtower:
        container_name: watchtower
        image: containrrr/watchtower:latest
        restart: unless-stopped
        # Watch containers where `com.centurylinklabs.watchtower.enable: true`
        # Update every day at 6 AM
        # seconds - minutes - hours - day of month - month - day of week
        command: --label-enable --schedule "0 0 6 * * *" --cleanup
        environment:
            TZ: ${TZ}
            WATCHTOWER_NOTIFICATIONS: slack
            WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "https://discord.com/api/webhooks/789836022820372480/mXeqD8HIMpMAfX1Lpzsm-Ntx0PBD6njmYxeNf3NiON70SQIym1n1mqaeaGPCa0XC_3kv/slack"
            WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: Watchtower
            WATCHTOWER_NOTIFICATIONS_LEVEL: info
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            com.centurylinklabs.watchtower.enable: true
        networks:
            - media-server

networks:
    media-server:
        driver: bridge
        name: media-server
