version: '3.6'
services:
  # Media Server
  plex:
    container_name: plex
    image: linuxserver/plex
    restart: unless-stopped
    ports:
      - "6000:32400"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      # Go to plex.tv/claim/ to claim your server
      - PLEX_CLAIM=
      - UMASK_SET=022 #optional
    volumes:
      - /docker/plex/config:/config
      - /docker/plex/transcode:/transcode
      - /docker/plex/data:/data
    networks:
      default:
        ipv4_address: 172.60.0.2
 
  # Plex Monitor
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli
    restart: unless-stopped
    ports:
      - "6001:8181"
    volumes:
      - ${USERDIR}/docker/tautulli/config:/config
      - ${USERDIR}/docker/tautulli/logs:/logs:ro
      - ${USERDIR}/docker/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      default:
        ipv4_address: 172.60.0.3
      
  # Movie Downloader and Manager
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - "6010:7878"
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - ${USERDIR}/downloads/completed:/downloads
      - ${USERDIR}/media/movies:/movies
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      default:
        ipv4_address: 172.60.0.4
      
  # Serie Downloader and Manager
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    ports:
        - "6011:8989"
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - ${USERDIR}/downloads/completed:/downloads
      - ${USERDIR}/media/tv:/tv
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      default:
        ipv4_address: 172.60.0.5
      
  # Proxy Server for Sonarr/Radarr search queries
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - "6012:9117"
    volumes:
      - ${USERDIR}/docker/jackett:/config
      - ${USERDIR}/downloads/completed:/downloads
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      default:
        ipv4_address: 172.60.0.6
      
  # Torrent Client
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    ports:
      - "6013:8112"
    volumes:
      - ${USERDIR}/docker/deluge:/config
      - ${USERDIR}/downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      default:
        ipv4_address: 172.60.0.7

  # Docker Image Automatic Updater
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: unless-stopped
    # Update everyday at 4 AM
    command: --schedule "0 0 4 * * *" --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 172.60.0.8
  
  # Web UI for Docker Containers. Usefull for managing the server
  # Not needed if you already have a Portainer installation on your server
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports:
      - "8081:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
    networks:
      default:
        ipv4_address: 172.60.0.9
      
networks:
  default:
    name: media-server-network
    ipam:
      config:
        - subnet: 172.60.0.0/24
