services: 
  jellyfin:
    image: jellyfin/jellyfin:10.9.11@sha256:fc1b51f4be3fba725e42dae2022d9c6a5b069acce01bef04d32fdee025dc511e
    container_name: jellyfin
    restart: unless-stopped
    cpus: 4
    mem_limit: 8192m
    user: ${UID}:${GID}
    environment:
      - TZ=${TZ}
      - DOCKER_MODS=lscr.io/linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ${USER_DIR}/jellyfin/config:/config
      - ${USER_DIR}/jellyfin/cache:/cache
      - /mnt/raid/media/movies:/movies:ro
      - /mnt/raid/media/music:/music:ro
      - /mnt/raid/media/series:/series:ro
      - /dev/shm:/data/transcode
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri # Intel/AMD GPU
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_NAME}`)
      - traefik.http.routers.jellyfin.middlewares=chain-no-auth@file
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
