version: "3.8"
services:
  # Music downloader and manager
  lidarr:
    image: linuxserver/lidarr:development
    container_name: lidarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/lidarr/config:/config
    - /mnt/raid/media-server/music:/music
    - /mnt/raid/media-server/downloads/completed:/downloads/completed
    expose:
    - 8686
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://music.davydehaas.nl/api/v1/system/status?apikey=${API_KEY_LIDARR} || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 2