version: "3.8"
services:
  # Torrent client with VPN
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
    - TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1,192.168.*.*
    - TRANSMISSION_RPC_USERNAME=${TORRENT_USERNAME}
    - TRANSMISSION_RPC_PASSWORD=${TORRENT_PASSWORD}
    - TRANSMISSION_RATIO_LIMIT=0
    - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    - TRANSMISSION_RENAME_PARTIAL_FILES=true
      # This will give the service read and execute permissions within the docker group
    - TRANSMISSION_UMASK=022
    - TRANSMISSION_DOWNLOAD_DIR=/downloads/completed
    - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
    - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
    - TRANSMISSION_WATCH_DIR=/downloads/watch
    - TRANSMISSION_WATCH_DIR_ENABLED=true
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - CREATE_TUN_DEVICE=true
    - WEBPROXY_ENABLED=false
      # Get access to the WebUI without VPN
    - LOCAL_NETWORK=192.168.0.0/24
      # Set these variables to the preferred VPN
    - OPENVPN_USERNAME=${VPN_USERNAME}
    - OPENVPN_PASSWORD=${VPN_PASSWORD}
      # NordVPN specific settings
    - OPENVPN_PROVIDER=NORDVPN
    - NORDVPN_COUNTRY=CH
    - NORDVPN_CATEGORY=P2P
    - NORDVPN_PROTOCOL=tcp
    volumes:
    - /media-server/transmission/config:/config
    - /media-server/transmission/data:/data
    - /media-server/downloads/watch:/downloads/watch
    - /media-server/downloads/completed:/downloads/completed
    - /media-server/downloads/incomplete:/downloads/incomplete
    ports:
    # Web UI
    - 9091:9091
    # Torrent Port
    - 51413:51413
    - 51413:51413/udp
    cap_add:
    - NET_ADMIN
    devices:
    # See (https://www.kernel.org/doc/Documentation/networking/tuntap.txt)
    - /dev/net/tun
    dns:
    - 1.1.1.1
    - 1.0.0.1
    labels:
    - com.centurylinklabs.watchtower.enable=true
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server