version: "3.8"
services:
  # Serie downloader and manager
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/sonarr/config:/config
    - /mnt/raid1/media-server/downloads/completed:/downloads/completed
    - /mnt/raid1/media-server/series:/series
    expose:
    - 8989
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true