version: "3.8"
services:
  # Music downloader and manager
  lidarr:
    image: linuxserver/lidarr:nightly
    container_name: lidarr
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/lidarr/config:/config
    - /media-server/music:/music
    - /media-server/downloads/completed:/downloads/completed
    expose:
    - 8686
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true