version: "3.9"
services:
  sabnzbd:
    image: linuxserver/sabnzbd:4.2.2@sha256:0048320fe830e5c6a06167ac57625b7777f7d1dff18c404181bd2bc2e6914e8f
    container_name: sabnzbd
    restart: unless-stopped
    cpus: 4
    mem_limit: 4096m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/sabnzbd:/config
      - /mnt/raid/media/downloads/completed:/downloads/completed
      - /mnt/raid/media/downloads/incomplete:/downloads/incomplete
    expose:
      # HTTP
      - 8080
      # HTTPS
      - 9090
      # healthcheck:
      #   test: ["CMD-SHELL", "curl -f https://usenet.${DOMAIN_NAME} || exit 1"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.entrypoints=websecure
      - traefik.http.routers.sabnzbd.tls=true
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN_NAME}`,`usenet.${DOMAIN_NAME}`)
      - traefik.http.routers.sabnzbd.middlewares=chain-authelia@file
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
