services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.3.3@sha256:cf7743af338e1cdfc97f6e6c605c8c45d737a4f268ab96ba6cec565134cea5e1
    container_name: sabnzbd
    restart: unless-stopped
    cpus: 4
    mem_limit: 4096m
    user: ${UID}:${GID}
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/sabnzbd:/config
      - /mnt/raid/media/downloads/completed:/downloads/completed
      - /mnt/raid/media/downloads/incomplete:/downloads/incomplete
    expose:
      # HTTP
      - 8080
      # HTTPS
      - 9090
      # healthcheck:
      #   test: ["CMD-SHELL", "curl -f https://usenet.${DOMAIN_NAME} || exit 1"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.entrypoints=websecure
      - traefik.http.routers.sabnzbd.tls=true
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${DOMAIN_NAME}`) || Host(`usenet.${DOMAIN_NAME}`)
      - traefik.http.routers.sabnzbd.middlewares=chain-authelia@file
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
