version: "3.8"
services:
  # Plex requests and user management system
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/ombi/config:/config
    expose:
    - 3579
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f https://requests.davydehaas.nl/api/v1/status || exit 1"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 2
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    - traefik.enable=true
    - traefik.http.routers.ombi.entrypoints=https
    - traefik.http.routers.ombi.tls=true
    - traefik.http.routers.ombi.rule=Host(`ombi.davydehaas.nl`)
    - traefik.http.routers.ombi.middlewares=chain-no-auth@file
    - traefik.http.routers.ombi.service=ombi
    - traefik.http.services.ombi.loadbalancer.server.port=3579
    networks:
    - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default