version: "3.8"
services:
# Movie downloader and manager
  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/radarr/config:/config
    - /media-server/downloads/completed:/downloads/completed
    - /media-server/movies:/movies
    ports:
    - 7878:7878
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true