version: "3.8"
services:
  # Proxy Server for Sonarr and prowlarr search queries
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/prowlarr/config:/config
    - /mnt/raid/media-server/downloads/completed:/downloads/completed
    - /mnt/raid/media-server/downloads/incomplete:/downloads/incomplete
    expose:
    - 9696
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://prowlarr.davydehaas.nl/ || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 2
