version: "3.7"
services:
  # Media server
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    hostname: plex
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      HOSTNAME: "Plex Server"
      VERSION: docker
    volumes:
    - /media-server/plex/config:/config
    - /media-server/plex/transcode:/transcode
    - /media-server/plex/data:/data
    - /media-server/movies:/movies:ro
    - /media-server/music:/music:ro
    - /media-server/series:/series:ro
    ports:
    # Plex Media Server
    - 32400:32400
    # Plex DLNA Server
    - 1900:1900/udp
    - 32469:32469
    # Plex Home Theater via Plex Companion
    - 3005:3005
    # Older Bonjour/Avahi network discovery
    #- "5353:5353/udp"
    # Plex for Roku via Plex Companion
    - 8324:8324
    # GDM network discovery
    - 32469:32469/udp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
    devices:
    - /dev/dri:/dev/dri # Intel/AMD GPU
    # - /dev/vchiq:/dev/vchiq # Raspberry Pi OpenMAX
    # - /dev/video10:/dev/video10 # Raspberry Pi V4L2
    # - /dev/video11:/dev/video11 # Raspberry Pi V4L2
    # - /dev/video12:/dev/video12 # Raspberry Pi V4L2
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server
