services:
  # Plex requests and user management system
  ombi:
    image: linuxserver/ombi:4.43.5@sha256:014ed9815d494fb95aa47fe4698a9a2a9c5371506bd04a1d5dbd8372b4ebf2c4
    container_name: ombi
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 512m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/ombi/config:/config
    expose:
      - 3579
      # healthcheck:
      #   test: ["CMD-SHELL", "curl -f https://requests.${DOMAIN_NAME}/api/v1/status || exit 1"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.ombi.entrypoints=websecure
      - traefik.http.routers.ombi.tls=true
      - traefik.http.routers.ombi.rule=Host(`requests.${DOMAIN_NAME}`,`ombi.${DOMAIN_NAME}`)
      - traefik.http.routers.ombi.middlewares=chain-authelia@file
      - traefik.http.services.ombi.loadbalancer.server.port=3579
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
