version: "3.9"
services:
  # Subtitles downloader and manager
  bazarr:
    image: linuxserver/bazarr:1.1.4
    container_name: bazarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/bazarr/config:/config
      - /mnt/raid/media/movies:/movies
      - /mnt/raid/media/series:/series
    expose:
      - 6767
      # healthcheck:
      #   test: ["CMD-SHELL", "curl -f https://subtitles.${DOMAIN_NAME}/api/systemstatus?apikey=${API_KEY_BAZARR} || exit 1"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.bazarr.entrypoints=websecure
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN_NAME}`,`subtitles.${DOMAIN_NAME}`)
      - traefik.http.routers.bazarr.middlewares=chain-authelia@file
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
