version: "3.8"
services:
  # Movie downloader and manager
  radarr:
    image: linuxserver/radarr:nightly
    container_name: radarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/radarr/config:/config
    - /mnt/raid/media-server/downloads/completed:/downloads/completed
    - /mnt/raid/media-server/movies:/movies
    expose:
    - 7878
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://movies.davydehaas.nl/api/system/status?apikey=${API_KEY_RADARR} || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 2