version: "3.8"
services:
  # Serie downloader and manager
  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/sonarr/config:/config
    - /media-server/downloads/completed:/downloads/completed
    - /media-server/series:/series
    ports:
    - 8989:8989
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server