version: "3.8"
services:
  # Proxy Server for Sonarr and Radarr search queries
  jackett:
    image: linuxserver/jackett:development
    container_name: jackett
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/jackett/config:/config/Jackett
    - /media-server/downloads/completed:/downloads/completed
    ports:
    - 9117:9117
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server