version: "3.8"
services:
  # Serie downloader and manager
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 2G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - ${USER_DIR}/sonarr/config:/config
    - /mnt/raid/media-server/downloads/completed:/downloads/completed
    - /mnt/raid/media-server/downloads/incomplete:/downloads/incomplete
    - /mnt/raid/media-server/series:/series
    expose:
    - 8989
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f https://series.davydehaas.nl/api/system/status?apikey=${API_KEY_SONARR} || exit 1"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 2
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    - traefik.enable=true
    - traefik.http.routers.sonarr.entrypoints=https
    - traefik.http.routers.sonarr.tls=true
    - traefik.http.routers.sonarr.rule=Host(`series.davydehaas.nl`)
    - traefik.http.routers.sonarr.middlewares=chain-no-auth@file
    - traefik.http.routers.sonarr.service=sonarr
    - traefik.http.services.sonarr.loadbalancer.server.port=8989
    networks:
    - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
