services:
  # Music downloader and manager
  lidarr:
    image: linuxserver/lidarr:2.3.3@sha256:2cb053dbc39f68f4d25c3f49d34f9c857ace45e289fcee277dc52c6660256fe9
    container_name: lidarr
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 256m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/lidarr/config:/config
      - /mnt/raid/media/downloads/completed:/downloads/completed
      - /mnt/raid/media/downloads/incomplete:/downloads/incomplete
      - /mnt/raid/media/music:/music
    expose:
      - 8686
      # healthcheck:
      #   test: ["CMD-SHELL", "curl -f https://music.${DOMAIN_NAME}/api/v1/system/status?apikey=${API_KEY_LIDARR} || exit 1"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.lidarr.entrypoints=websecure
      - traefik.http.routers.lidarr.tls=true
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN_NAME}`,`music.${DOMAIN_NAME}`)
      - traefik.http.routers.lidarr.middlewares=chain-authelia@file
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
