version: "3.8"
services:
  # Music downloader and manager
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - ${USER_DIR}/lidarr/config:/config
    - /mnt/raid/media-server/downloads/completed:/downloads/completed
    - /mnt/raid/media-server/downloads/incomplete:/downloads/incomplete
    - /mnt/raid/media-server/music:/music
    expose:
    - 8686
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f https://music.$DOMAIN_NAME/api/v1/system/status?apikey=${API_KEY_LIDARR} || exit 1"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 2
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    - traefik.enable=true
    - traefik.http.routers.lidarr.entrypoints=https
    - traefik.http.routers.lidarr.tls=true
    - traefik.http.routers.lidarr.rule=Host(`lidarr.$DOMAIN_NAME`,`music.$DOMAIN_NAME`)
    - traefik.http.routers.lidarr.middlewares=chain-no-auth@file
    - traefik.http.services.lidarr.loadbalancer.server.port=8686
    networks:
    - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default