version: "3.8"
services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/sabnzbd:/config
    - /mnt/raid/media-server/downloads/completed:/downloads/completed
    - /mnt/raid/media-server/downloads/incomplete:/downloads/incomplete
    expose:
    - 8080 # HTTP
    - 9090 # HTTPS
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f https://usenet.davydehaas.nl || exit 1"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 2
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    - traefik.enable=true
    - traefik.http.routers.sabnzbd.entrypoints=https
    - traefik.http.routers.sabnzbd.tls=true
    - traefik.http.routers.sabnzbd.rule=Host(`usenet.davydehaas.nl`)
    - traefik.http.routers.sabnzbd.middlewares=chain-no-auth@file
    - traefik.http.routers.sabnzbd.service=sabnzbd
    - traefik.http.services.sabnzbd.loadbalancer.server.port=9090
    networks:
    - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
