version: "3.8"
services:
  # Plex monitor
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/plex/config:/plex/config:ro
    - /media-server/tautulli/config:/config
    - /media-server/tautulli/logs:/logs
    expose:
    - 8181
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --quiet --tries=1 --spider https://tautulli.davydehaas.nl/status || exit 1"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 2
    