version: "3.8"
services:
  # Media stream service
  emby:
    image: linuxserver/emby:latest
    container_name: emby
    restart: unless-stopped
    cpus: 4
    mem_limit: 8G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/emby/config:/config
    - /media-server/emby/transcode:/transcode
    - /mnt/raid/media-server/movies:/movies:ro
    - /mnt/raid/media-server/music:/music:ro
    - /mnt/raid/media-server/series:/series:ro
    #- /opt/vc/lib:/opt/vc/lib # OpenMAX lib
    expose:
    - 8096 # HTTP Web UI
    - 8920 # HTTPS Web UI
    devices:
    - /dev/dri:/dev/dri # Intel/AMD GPU
    #- /dev/vchiq:/dev/vchiq # Raspberry Pi OpenMAX
    #- /dev/video10:/dev/video10 # Raspberry Pi V4L2
    #- /dev/video11:/dev/video11 # Raspberry Pi V4L2
    #- /dev/video12:/dev/video12 # Raspberry Pi V4L2
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
  embystat:
    image: linuxserver/embystat:latest
    container_name: embystat
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/embystat/config:/config
    expose:
    - 6555
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true