services:
  # Plex monitor
  tautulli:
    image: lscr.io/linuxserver/tautulli:2.14.5@sha256:8e86ebd55560c78190ff21c32726567d0e8eedc54c4133e508871e76fbab2046
    container_name: tautulli
    restart: unless-stopped
    cpus: 4
    mem_limit: 2048m
    # user: ${UID}:${GID}
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/plex/config:/plex/config:ro
      - ${USER_DIR}/tautulli/config:/config
      - ${USER_DIR}/tautulli/logs:/logs
    expose:
      - 8181
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://tautulli:8181/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.tautulli.entrypoints=websecure
      - traefik.http.routers.tautulli.tls=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN_NAME}`)
      - traefik.http.routers.tautulli.middlewares=chain-no-auth@file
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
    
