services:
  # Plex requests and user management system
  overseerr:
    image: linuxserver/overseerr:1.33.2@sha256:edac39725d48761481c02107d3077a825c3cab207e0565b8b213ced5143706ea
    container_name: overseerr
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 512m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/overseerr/config:/config
    expose:
      - 5055
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.overseerr.entrypoints=websecure
      - traefik.http.routers.overseerr.tls=true
      - traefik.http.routers.overseerr.rule=Host(`overseerr.${DOMAIN_NAME}`)
      - traefik.http.routers.overseerr.middlewares=chain-authelia@file
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
