version: "3.8"
services:
  # Torrent client with VPN
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: unless-stopped
    cpus: 2
    mem_limit: 4G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    - CREATE_TUN_DEVICE=true
    - DROP_DEFAULT_ROUTE=true
    - HEALTH_CHECK_HOST=twitter.com
      # Get access to the WebUI without VPN
    - LOCAL_NETWORK=192.168.0.0/24
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      # Set these variables to the preferred VPN
    - OPENVPN_USERNAME=${VPN_USERNAME}
    - OPENVPN_PASSWORD=${VPN_PASSWORD}
      # NordVPN specific settings
    - OPENVPN_PROVIDER=NORDVPN
    - NORDVPN_COUNTRY=CH
    - NORDVPN_CATEGORY=P2P
    - NORDVPN_PROTOCOL=tcp
    - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
    - TRANSMISSION_ENCRYPTION=2 # Require encrypted connections
    - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
    - TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1,192.168.*.*
    - TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=true
    - TRANSMISSION_RPC_USERNAME=${TORRENT_USERNAME}
    - TRANSMISSION_RPC_PASSWORD=${TORRENT_PASSWORD}
    - TRANSMISSION_SPEED_LIMIT_UP=0
    - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
    - TRANSMISSION_RATIO_LIMIT=0
    - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    - TRANSMISSION_DOWNLOAD_DIR=/downloads/completed
    - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
    - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true
    - TRANSMISSION_RENAME_PARTIAL_FILES=true
    - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true
      # This will give the service read and execute permissions within the docker group
    - TRANSMISSION_UMASK=022
    - TRANSMISSION_WEB_UI=flood # combustion, kettu, transmission-web-control or flood
    - WEBPROXY_ENABLED=false
    volumes:
    - /media-server/transmission/config:/config
    - /media-server/transmission/data:/data
    - /mnt/raid/media-server/downloads/completed:/downloads/completed
    - /mnt/raid/media-server/downloads/incomplete:/downloads/incomplete
    expose:
    # Web UI
    - 9091
    ports:
    # Torrent Ports
    - 51413:51413
    - 51413:51413/udp
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    cap_add:
    - NET_ADMIN
    dns:
    - 1.1.1.1
    - 1.0.0.1