version: "3.8"
services:
  # Plex requests and user management system
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/ombi/config:/config
    expose:
    - 3579
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://requests.davydehaas.nl/api/v1/status || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 2