services:
  # Music downloader and manager
  lidarr:
    image: lscr.io/linuxserver/lidarr:2.5.3@sha256:c3d8c0970b0e5a7dce0b29930efc83ab33a0fff8d1afbfca88a2104affb80c45
    container_name: lidarr
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 256m
    # user: ${UID}:${GID}
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/lidarr/config:/config
      - /mnt/raid/media/downloads/completed:/downloads/completed
      - /mnt/raid/media/downloads/incomplete:/downloads/incomplete
      - /mnt/raid/media/music:/music
    expose:
      - 8686
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://lidarr:8686/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      start_interval: 5s
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.lidarr.entrypoints=websecure
      - traefik.http.routers.lidarr.tls=true
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN_NAME}`) || Host(`music.${DOMAIN_NAME}`)
      - traefik.http.routers.lidarr.middlewares=chain-authelia@file
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
