version: "3.7"
services:
  # Proxy Server for Sonarr & Radarr search queries
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
    - /media-server/jackett/config:/config/Jackett
    - /media-server/downloads/completed:/downloads/completed
    ports:
    - 9117:9117
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server