version: "3.8"
services:
  # Plex monitor
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/tautulli/config:/config
    - /media-server/tautulli/logs:/logs
    - /media-server/plex/config:/plex/config:ro
    expose:
    - 8181
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true