services:
  # Music downloader and manager
  lidarr:
    image: lscr.io/linuxserver/lidarr:2.5.3@sha256:1a543b03bbb76a6683bbbe77e4366917f0e7eae67f2e5e6c005dd40344ec7008
    container_name: lidarr
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 256m
    user: ${UID}:${GID}
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/lidarr/config:/config
      - /mnt/raid/media/downloads/completed:/downloads/completed
      - /mnt/raid/media/downloads/incomplete:/downloads/incomplete
      - /mnt/raid/media/music:/music
    expose:
      - 8686
      # healthcheck:
      #   test: ["CMD-SHELL", "curl -f https://music.${DOMAIN_NAME}/api/v1/system/status?apikey=${API_KEY_LIDARR} || exit 1"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.lidarr.entrypoints=websecure
      - traefik.http.routers.lidarr.tls=true
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN_NAME}`) || Host(`music.${DOMAIN_NAME}`)
      - traefik.http.routers.lidarr.middlewares=chain-authelia@file
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
