services:
  # Plex monitor
  tautulli:
    image: linuxserver/tautulli:2.14.2@sha256:99ff955b1b4ffbb2738aa3b0b612c9f59ab9d05730d38f95684189036429b509
    container_name: tautulli
    restart: unless-stopped
    cpus: 4
    mem_limit: 2048m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/plex/config:/plex/config:ro
      - ${USER_DIR}/tautulli/config:/config
      - ${USER_DIR}/tautulli/logs:/logs
    expose:
      - 8181
      # healthcheck:
      #   test: ["CMD-SHELL", "wget --quiet --tries=1 --spider https://tautulli.${DOMAIN_NAME}/status || exit 1"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.tautulli.entrypoints=websecure
      - traefik.http.routers.tautulli.tls=true
      - traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN_NAME}`)
      - traefik.http.routers.tautulli.middlewares=chain-no-auth@file
      - traefik.http.services.tautulli.loadbalancer.server.port=8181
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
    
