version: "3.8"
services:
  # Serie downloader and manager
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/sonarr/config:/config
    - /mnt/raid/media-server/downloads/completed:/downloads/completed
    - /mnt/raid/media-server/downloads/incomplete:/downloads/incomplete
    - /mnt/raid/media-server/series:/series
    expose:
    - 8989
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://series.davydehaas.nl/api/system/status?apikey=${API_KEY_SONARR} || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 2