version: "3.7"
services:
  # Web UI for Docker containers
  # Useful for managing all the containers on the server
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/portainer/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 9000:9000
    labels:
    - com.centurylinklabs.watchtower.enable=true
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server