version: "3.8"
services:
  # Plex requests and user management system
  overseerr:
    image: linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - ${USER_DIR}/overseerr/config:/config
    expose:
    - 5055
    labels:
    - diun.enable=true
    - diun.watch_repo=true
    - traefik.enable=true
    - traefik.http.routers.overseerr.entrypoints=websecure
    - traefik.http.routers.overseerr.tls=true
    - traefik.http.routers.overseerr.rule=Host(`overseerr.$DOMAIN_NAME`)
    - traefik.http.routers.overseerr.middlewares=chain-no-auth@file
    - traefik.http.services.overseerr.loadbalancer.server.port=5055
    networks:
    - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default