version: "3.8"
services:
  # Proxy Server for Sonarr and Radarr search queries
  jackett:
    image: linuxserver/jackett:development
    container_name: jackett
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/jackett/config:/config/Jackett
    - /mnt/raid1/media-server/downloads/completed:/downloads/completed
    expose:
    - 9117
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true