services:
  # Proxy Server for Sonarr and prowlarr search queries
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.24.3@sha256:a6fc8ab9ff34d82327d29f8b5bfb7a672c0e54a274e5e5b023db01c335d05dfd
    container_name: prowlarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1024m
    # user: ${UID}:${GID}
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/prowlarr/config:/config
      - /mnt/raid/media/downloads/completed:/downloads/completed
      - /mnt/raid/media/downloads/incomplete:/downloads/incomplete
    expose:
      - 9696
  #     healthcheck:
  #       test: ["CMD-SHELL", "curl -f https://prowlarr.${DOMAIN_NAME}/ || exit 1"]
  #       interval: 60s
  #       timeout: 10s
  #       retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN_NAME}`)
      - traefik.http.routers.prowlarr.middlewares=chain-authelia@file
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
