version: "3.8"
services:
  # Subtitles downloader and manager
  bazarr:
    image: linuxserver/bazarr:development
    container_name: bazarr
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/bazarr/config:/config
    - /mnt/raid/media-server/movies:/movies
    - /mnt/raid/media-server/series:/series
    expose:
    - 6767
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true