version: "3.7"
services:
  # Plex requests and user management system
  ombi:
    image: linuxserver/ombi:v4-preview
    container_name: ombi
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/ombi/config:/config
    ports:
    - 3579:3579
    labels:
    - com.centurylinklabs.watchtower.enable=true
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server