version: "3.8"
services:
  # Movie downloader and manager
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 2G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - ${USER_DIR}/radarr/config:/config
    - /mnt/raid/media-server/downloads/completed:/downloads/completed
    - /mnt/raid/media-server/downloads/incomplete:/downloads/incomplete
    - /mnt/raid/media-server/movies:/movies
    expose:
    - 7878
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f https://movies.davydehaas.nl/api/system/status?apikey=${API_KEY_RADARR} || exit 1"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 2
    labels:
    - com.centurylinklabs.watchtower.enable=true
    - diun.enable=true
    - diun.watch_repo=true
    - traefik.enable=true
    - traefik.http.routers.radarr.entrypoints=websecure
    - traefik.http.routers.radarr.rule=Host(`radarr.davydehaas.nl`,`movies.$DOMAIN_NAME`)
    - traefik.http.routers.radarr.middlewares=chain-no-auth@file
    - traefik.http.services.radarr.loadbalancer.server.port=7878
    networks:
    - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
