services:
  # Movie downloader and manager
  radarr:
    image: linuxserver/radarr:5.8.3@sha256:9d6f0548fd805edb30108fdd06d0fc5a4436c9bd708b57bd4119d7aefa815fe4
    container_name: radarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 4096m
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/radarr/config:/config
      - /mnt/raid/media/downloads/completed:/downloads/completed
      - /mnt/raid/media/downloads/incomplete:/downloads/incomplete
      - /mnt/raid/media/movies:/movies
    expose:
      - 7878
      # healthcheck:
      #   test: ["CMD-SHELL", "curl -f https://movies.${DOMAIN_NAME}/api/system/status?apikey=${API_KEY_RADARR} || exit 1"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`) || Host(`movies.${DOMAIN_NAME}`)
      - traefik.http.routers.radarr.middlewares=chain-authelia@file
      - traefik.http.services.radarr.loadbalancer.server.port=7878
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
