version: "3.7"

services:
  tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    cpus: 2
    mem_limit: 1G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK_SET=002
      - serverIP=tdarr
      - serverPort=8266
      - webUIPort=8265
    volumes:
      - ${USER_DIR}/tdarr/config:/app/configs
      - ${USER_DIR}/tdarr/logs:/app/logs
      - ${USER_DIR}/tdarr/server:/app/server
      - ${USER_DIR}/tdarr/transcode_cache:/temp
      - /mnt/raid/media-server/movies:/movies
      - /mnt/raid/media-server/series:/series
    ports:
      - 8266:8266
      - 8265:8265
      - 8267:8267
    expose:
      - 8265
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.entrypoints=websecure
      - traefik.http.routers.tdarr.rule=Host(`tdarr.$DOMAIN_NAME`)
      - traefik.http.routers.tdarr.tls=true
      - traefik.http.routers.tdarr.middlewares=chain-oauth@file
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
    networks:
      - reverse-proxy
  tdarr-node:
    image: haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    restart: unless-stopped
    cpus: 2
    mem_limit: 1G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - UMASK_SET=002
      - nodeID=MainNode
      - nodeIP=tdarr-node
      - nodePort=8267
      - serverIP=tdarr
      - serverPort=8266
    volumes:
      - /media-server/tdarr/config:/app/configs
      - /media-server/tdarr/logs:/app/logs
      - /media-server/tdarr/transcode_cache:/temp
      - /mnt/raid/media-server/movies:/movies
      - /mnt/raid/media-server/series:/series
    devices:
      - /dev/dri:/dev/dri
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
