networks:
  reverse-proxy:
    external: true

services:
  # Media stream service
  emby:
    image: lscr.io/linuxserver/emby:4.7.11
    container_name: emby
    cpus: 4
    mem_limit: 8G
    restart: unless-stopped
    expose:
      # HTTP Web UI
      - 8096
      # HTTPS Web UI
      - 8920
    networks:
      - reverse-proxy
    devices:
      # Intel/AMD GPU
      - /dev/dri:/dev/dri
      # Raspberry Pi OpenMAX
      #- /dev/vchiq:/dev/vchiq
      # Raspberry Pi V4L2
      #- /dev/video10:/dev/video10
      #- /dev/video11:/dev/video11
      #- /dev/video12:/dev/video12
    volumes:
      - ${USER_DIR}/emby/config:/config
      - ${USER_DIR}/emby/transcode:/transcode
      - /mnt/raid/media/movies:/movies:ro
      - /mnt/raid/media/music:/music:ro
      - /mnt/raid/media/series:/series:ro
      # - /opt/vc/lib:/opt/vc/lib # OpenMAX lib
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    labels:
      - diun.enable=true
