networks:
  reverse-proxy:
    external: true

services:
  # Plex requests and user management system
  ombi:
    image: lscr.io/linuxserver/ombi:4.44.1@sha256:f7eabee4800cd7a4716391aca11770563f5045f55cb10f2a397d94ac33d5f0b1
    container_name: ombi
    cpus: 0.5
    mem_limit: 512m
    restart: unless-stopped
    expose:
      - 3579
    networks:
      - reverse-proxy
    volumes:
      - ${USER_DIR}/ombi/config:/config
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.ombi.entrypoints=websecure
      - traefik.http.routers.ombi.tls=true
      - traefik.http.routers.ombi.rule=Host(`requests.${DOMAIN_NAME}`) || Host(`ombi.${DOMAIN_NAME}`)
      - traefik.http.routers.ombi.middlewares=chain-authelia@file
      - traefik.http.services.ombi.loadbalancer.server.port=3579
