services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    user: ${UID}:${GID}
    environment:
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/organizr/config:/config
    expose:
      - 80
    labels:
      - diun.enable=true