version: "3.8"
services:
  kodi:
    image: celedhrim/kodi-server:leia
    container_name: kodi
    restart: unless-stopped
    cpus: 4
    mem_limit: 8G
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/kodi/config:/config/.kodi
    ports:
    - 8080:8080 # Web UI
    - 9090:9090 # Websockets
    - 9777:9777/udp # Esall interface
    labels:
    - com.centurylinklabs.watchtower.enable=true