version: "3.7"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    volumes:
    - /media-server/heimdall/config:/config
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    labels:
    - com.centurylinklabs.watchtower.enable=true
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server