version: "3.8"
services:
  # Torrent client without VPN
  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    - DELUGE_LOGLEVEL=error
    volumes:
    - /media-server/deluge/config:/config
    - /media-server/downloads:/root/Downloads
    ports:
    # Web UI
    - 8112:8112
    # Incoming Connections (Used for seeding)
    - 53160:53160
    - 53160:53160/udp
    # Daemon remote port (Used for GTK applications)
    - 58846:58846
    labels:
    - com.centurylinklabs.watchtower.enable=true
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server