services:
  # Proxy Server for Sonarr and Radarr search queries
  jackett:
    image: lscr.io/linuxserver/jackett:0.20.3870
    container_name: jackett
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    user: ${UID}:${GID}
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/jackett/config:/config/Jackett
      - /mnt/raid/media/downloads/completed:/downloads/completed
      - /mnt/raid/media/downloads/incomplete:/downloads/incomplete
    expose:
      - 9117
      # healthcheck:
      #   test: ["CMD-SHELL", "curl -f https://jackett.${DOMAIN_NAME} || exit 1"]
      #   interval: 60s
      #   timeout: 10s
      #   retries: 2
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.jackett.entrypoints=websecure
      - traefik.http.routers.jackett.tls=true
      - traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN_NAME}`)
      - traefik.http.routers.jackett.middlewares=chain-no-auth@file
      - traefik.http.services.jackett.loadbalancer.server.port=9117
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
