version: "3.7"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
    - /media-server/heimdall/config:/config
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server