services:
  # Plex requests and user management system
  overseerr:
    image: lscr.io/linuxserver/overseerr:1.33.2@sha256:aaba9e51b62a17e914de79e8eda4616f12e9bf4bce115cda6d0ad8178daea102
    container_name: overseerr
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 512m
    user: ${UID}:${GID}
    environment:
      - PGID=${GID}
      - PUID=${UID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/overseerr/config:/config
    expose:
      - 5055
    labels:
      - diun.enable=true
      - traefik.enable=true
      - traefik.http.routers.overseerr.entrypoints=websecure
      - traefik.http.routers.overseerr.tls=true
      - traefik.http.routers.overseerr.rule=Host(`overseerr.${DOMAIN_NAME}`)
      - traefik.http.routers.overseerr.middlewares=chain-authelia@file
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy_default
