version: "3.7"
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      LOG_LEVEL: info
      LOG_JSON: "false"
      DIUN_WATCH_WORKERS: 20
      DIUN_WATCH_SCHEDULE: 0 */6 * * *
      DIUN_PROVIDERS_DOCKER: "true"
      DIUN_PROVIDERS_DOCKER_WATCHSTOPPED: "true"
    volumes:
      - /media-server/diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      diun.enable: "true"
      diun.watch_repo: "true"
      com.centurylinklabs.watchtower.enable: "true"
    networks:
    - media-server
networks:
  media-server:
    driver: bridge
    name: media-server