version: "3.9"
services:
  # Media stream service
  emby:
    image: linuxserver/emby:latest
    container_name: emby
    restart: unless-stopped
    cpus: 4
    mem_limit: 8G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/emby/config:/config
      - ${USER_DIR}/emby/transcode:/transcode
      - /mnt/raid/media/movies:/movies:ro
      - /mnt/raid/media/music:/music:ro
      - /mnt/raid/media/series:/series:ro
      # - /opt/vc/lib:/opt/vc/lib # OpenMAX lib
    expose:
      # HTTP Web UI
      - 8096
      # HTTPS Web UI
      - 8920
    devices:
      # Intel/AMD GPU
      - /dev/dri:/dev/dri
      # Raspberry Pi OpenMAX
      #- /dev/vchiq:/dev/vchiq
      # Raspberry Pi V4L2
      #- /dev/video10:/dev/video10
      #- /dev/video11:/dev/video11
      #- /dev/video12:/dev/video12
    labels:
      - diun.enable=true
  embystat:
    image: linuxserver/embystat:latest
    container_name: embystat
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/embystat/config:/config
    expose:
      - 6555
    labels:
      - diun.enable=true
