version: "3.9"
services:
  # Media stream service
  kodi:
    image: celedhrim/kodi-server:matrix
    container_name: kodi
    restart: unless-stopped
    cpus: 4
    mem_limit: 8G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${USER_DIR}/kodi/config:/config/.kodi
      - /mnt/raid/media/movies:/movies:ro
      - /mnt/raid/media/music:/music:ro
      - /mnt/raid/media/series:/series:ro
    expose:
      # Web UI
      - 8080
      # Websockets
      - 9090
      # Esall interface
      - 9777/udp
    labels:
      - diun.enable=true
