name: Deploy media-server

on:
  push:
    branches: 
    - main

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  TARGET_DIR: /opt/compose/media-server/
  PGID: 1000
  PUID: 1000
  TZ: Etc/UTC
  USER_DIR: /opt/appdata/media-server/
  DOMAIN_NAME: davydehaas.nl

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.3.0
    - name: SSH SCP | Copy docker-compose.yml
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        #password: ${{ secrets.SSH_PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: enabled/docker-compose.*.yml
        target: ${{ env.TARGET_DIR }}
        strip_components: 1 # strip /enabled
        rm: true # remove target folder before uploading data
    - name: SSH | Start containers
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        #password: ${{ secrets.SSH_PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd ${{ env.TARGET_DIR }}
          
          echo 'PGID=${{ env.PGID }}' >> .env
          echo 'PUID=${{ env.PUID }}' >> .env
          echo 'TZ=${{ env.TZ }}' >> .env
          echo 'USER_DIR=${{ env.USER_DIR }}' >> .env
          echo 'DOMAIN_NAME=${{ env.DOMAIN_NAME }}' >> .env
          
          echo 'TORRENT_USERNAME=${{ secrets.TORRENT_USERNAME }}' >> .env
          echo 'TORRENT_PASSWORD=${{ secrets.TORRENT_PASSWORD }}' >> .env
          echo 'VPN_USERNAME=${{ secrets.VPN_USERNAME }}' >> .env
          echo 'VPN_PASSWORD=${{ secrets.VPN_PASSWORD }}' >> .env
          
          echo 'API_KEY_BAZARR=${{ secrets.API_KEY_BAZARR }}' >> .env
          echo 'API_KEY_LIDARR=${{ secrets.API_KEY_LIDARR }}' >> .env
          echo 'API_KEY_RADARR=${{ secrets.API_KEY_RADARR }}' >> .env
          echo 'API_KEY_SONARR=${{ secrets.API_KEY_SONARR }}' >> .env

          docker compose $(find docker-compose.*.yml | sed -e 's/^/-f /') up -d --remove-orphans
