name: Deploy media-server

on:
  push:
    branches: 
    - main

env:
  TARGET_DIRECTORY: ./docker/media-server
  TZ: Europe/Amsterdam

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH SCP | Copy docker-compose.yml
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "docker-compose.yml"
        target: ${{ env.TARGET_DIRECTORY }}
    - name: SSH | Start container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ env.TARGET_DIRECTORY }}
          echo 'TZ=${{ env.TZ }}' > .env
          docker-compose down
          docker-compose up -d
