name: Deploy media-server

on:
  push:
    branches: 
    - main

env:
  TARGET_DIRECTORY: /media-server
  TZ: America/New_York

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH SCP | Copy container configurations
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: ./enabled/docker-compose.*.yml
        target: ${{ env.TARGET_DIRECTORY }}
    - name: SSH | Start containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd ${{ env.TARGET_DIRECTORY }}/enabled
          echo 'TZ=${{ env.TZ }}' > .env
          docker-compose $(find docker-compose.*.yml | sed -e 's/^/-f /') down --remove-orphans
          docker-compose -p media-server $(find docker-compose.*.yml | sed -e 's/^/-f /') up -d
