name: Deploy media-server

on:
  push:
    branches: 
    - main

env:
  TARGET_DIRECTORY: ./docker-compose/media-server
  PGID: 998
  PUID: 997
  TZ: "Europe/Amsterdam"
  TORRENT_USERNAME: ${{ secrets.TORRENT_USERNAME }}
  TORRENT_PASSWORD: ${{ secrets.TORRENT_PASSWORD }}
  VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
  VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH SCP | Copy container configurations
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: enabled/docker-compose.*.yml
        target: ${{ env.TARGET_DIRECTORY }}
        strip_components: 1
        rm: true
    - name: SSH | Start containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd ${{ env.TARGET_DIRECTORY }}
          
          echo 'PGID=${{ env.PGID }}' >> .env
          echo 'PUID=${{ env.PUID }}' >> .env
          echo 'TZ=${{ env.TZ }}' >> .env
          echo 'TORRENT_USERNAME=${{ env.TORRENT_USERNAME }}' >> .env
          echo 'TORRENT_PASSWORD=${{ env.TORRENT_PASSWORD }}' >> .env
          echo 'VPN_USERNAME=${{ env.VPN_USERNAME }}' >> .env
          echo 'VPN_PASSWORD=${{ env.VPN_PASSWORD }}' >> .env

          docker-compose $(find docker-compose.*.yml | sed -e 's/^/-f /') up -d
